import styles from "./Header.module.scss"
import ReactTooltip from "react-tooltip"

export default function Header() {
  return (
    <div className={styles.header}>
      <h1 className={styles.mainHeading}>effects of eu exports on employment and income</h1>
      <nav className={styles.navigation}>
        <h4 className={styles.navHeading}>choose a map mode</h4>
        <ul>
          <li className={styles.active}>EU jobs supported bu EU exports</li>
          <li>EU income generated by EU exports</li>
          <span className={styles.divider}></span>
          <li>Jobs outside EU supported by EU exports</li>
          <li>Income generated outside EU by EU exports</li>
        </ul>
      </nav>
    </div>
  )
}
